Repository CSCMU-65s/prerequisite-tree, pull requests merged in 2023-06, with the labels that each got.

#53 main
  .github/workflows/codeql.yml
  src/css/tree.css
  src/index.html
  src/js/tree.js
Labels: enhancement

#54 Node highlight and more are available now!!!
  .github/workflows/codeql.yml
  src/index.html
  src/js/tree.js
Labels: enhancement

#63 Update wiki
  README.md
Labels: documentation

#68 add Qodana action to workflows
  .github/workflows/code_quality.yml
  .idea/fileColors.xml
  .idea/jsLibraryMappings.xml
  .idea/prettier.xml
  README.md
  qodana.yaml
Labels: dependencies

#73 Unittest
  .github/labeler.yml
  .github/workflows/labeler.yml
Labels: labels, rules

#74 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: labels, rules

#76 Improve project to relate Community Standards
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE.md
Labels: labels, rules

#80 update coloursheme
  docs/css/main.css
  docs/css/tree.css
  docs/index.html
  docs/js/tree.js
Labels: bug, labels, rules

#78 Ta
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  SECURITY.md
  docs/css/main.css
  docs/css/tree.css
  docs/index.html
  docs/js/tree.js
  qodana.yaml
Labels: labels, rules

#81 fix merge error
  docs/css/main.css
  docs/css/tree.css
  docs/index.html
  docs/js/tree.js
Labels: bug, labels, rules

#82 change from fill with white colour to reduce opacity of nodes
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/workflows/labeler.yml
  .gitpod.yml
  .vscode/settings.json
  SECURITY.md
  docs/css/main.css
  docs/css/tree.css
  docs/index.html
  docs/js/tree.js
  package-lock.json
  qodana.yaml
Labels: enhancement, labels, rules

#83 Add Mention to Script and Sample Table for Course Detail
  .gitpod.yml
  .idea/prettier.xml
  README.md
  docs/img/tree_view_screenshot.png
Labels: labels, rules

#84 Refactor Upgrade Script, Update Documentation, and Add Faded Out Lines
  .idea/prerequisite-tree.iml
  README.md
  docs/css/main.css
  docs/js/tree.js
Labels: enhancement, labels, rules

#88 Merge from main into unittest
  .github/labeler.yml
  .gitpod.yml
  .idea/jsLibraryMappings.xml
  .idea/prerequisite-tree.iml
  .idea/prettier.xml
  .vscode/settings.json
  README.md
  docs/css/main.css
  docs/img/tree_view_screenshot.png
  docs/js/tree.js
  package-lock.json
Labels: enhancement, labels, rules

#89 Update: Color theme, repository transfer, node transition, and navbar position fix
  .idea/inspectionProfiles/Project_Default.xml
  .space.kts
  README.md
  docs/css/main.css
  docs/css/popout.css
  docs/css/tree.css
  docs/index.html
  docs/js/tree.js
Labels: enhancement, labels, rules
